# Generated by Django 3.1.2 on 2021-01-24 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('product', '0129_add_product_types_and_attributes_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant'),
            preserve_default=False,
        ),
    ]
