# Generated by Django 3.1.2 on 2021-02-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0130_auto_20210124_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='merchant',
        ),
    ]
