# Generated by Django 3.1.2 on 2021-03-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_remove_productvariant_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_types',
            field=models.ManyToManyField(blank=True, to='product.ProductType'),
        ),
    ]
