# Generated by Django 3.1.2 on 2021-01-09 18:25

from django.db import migrations, models
import saleor.account.models
import saleor.sms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', saleor.account.models.PossiblePhoneNumberField(max_length=128, region=None)),
                ('code', models.CharField(default=saleor.sms.models._generate_sms_code, max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
