# Generated by Django 3.1.2 on 2021-01-09 16:21

from django.db import migrations, models
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=saleor.account.models.PossiblePhoneNumberField(default='+77770223046', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
