# Generated by Django 3.1.2 on 2021-01-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20210109_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
